name: action
description: Create a custom action:v1
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name for the generated Docker image"
    required: true
  tag_name:
    description: "Tag to be added to the final image"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Build the Docker image
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo TAG=$(date +%s) >> $GITHUB_ENV
        else
          echo TAG="${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Docker image
      run: |
        NAME="${{ inputs.image_name }}:$TAG"
        docker build . --file ${{ inputs.path_dockerfile }} --tag $NAME
        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV
      shell: bash
