name: action
description: Create a custom action:v1
inputs:
  input-name:
    description: "input-description"
    required: true
    default: "default-value"
runs:
  using: composite
  steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academy:$(date +%s)
      shell: bash
