name: action
description: Create a custom action:v1
inputs:
  input-name:
    description: "input-description"
    required: true
    default: "default-value"
runs:
  using: composite
  steps:
    - run: |
        echo "Hello World"
      shell: bash